name: Gitbu continues integration test

on: 
  push: 
    on-branch: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout node
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
        working-directory: nestjs-ci

      - name: Run Test
        run: npm run test
        working-directory: nestjs-ci

      - name: Run linter
        run: npm run lint

      - name: Run build
        run: npm run build

